"use client";
import { FormEvent, useState } from "react";
import type { Paper } from "@/lib/papers/types";
type Context={paperId:string;page:number;selectedText:string};
export function StudyChat({paper,context,onClearSelection}:{paper:Paper;context:Context;onClearSelection:()=>void}) {
 const [input,setInput]=useState(""); const [notice,setNotice]=useState("");
 async function submit(e:FormEvent){e.preventDefault();if(!input.trim())return;const r=await fetch("/api/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:input,context})});const d=await r.json();setNotice(d.message);}
 return <aside className="flex min-h-[520px] flex-col border-t border-[var(--line)] bg-[#0d1210] lg:min-h-0 lg:border-l lg:border-t-0" aria-label="학습 대화"><header className="border-b border-[var(--line)] p-4"><p className="text-xs text-[var(--accent)]">STUDY CHAT</p><h2 className="mt-1 font-medium">논문에 질문하기</h2></header><div className="flex-1 p-4"><div className="rounded-xl border border-[#26312c] bg-[#131916] p-4 text-sm leading-relaxed text-[#aab4af]">AI 제공자가 아직 설정되지 않았습니다. 현재 페이지, 선택 텍스트, 관련 청크만 전달하는 교체 가능한 인터페이스가 준비되어 있습니다.</div>{notice&&<p role="status" className="mt-4 text-sm text-[var(--muted)]">{notice}</p>}</div><form onSubmit={submit} className="border-t border-[var(--line)] p-4">{context.selectedText&&<div className="mb-2 rounded-lg bg-[#19251f] p-2 text-xs"><div className="flex justify-between"><span className="text-[var(--accent)]">선택 텍스트 · p.{context.page}</span><button type="button" onClick={onClearSelection}>제거</button></div><p className="mt-1 line-clamp-3 text-[#b7c0bc]">{context.selectedText}</p></div>}<label htmlFor="chat" className="sr-only">질문</label><textarea id="chat" rows={3} value={input} onChange={e=>setInput(e.target.value)} placeholder={`${paper.title}에 관해 질문하세요…`} className="w-full resize-none rounded-xl border border-[var(--line)] bg-[#151b18] p-3 text-sm"/><div className="mt-2 flex items-center justify-between"><span className="text-xs text-[var(--muted)]">문맥: p.{context.page}</span><button className="rounded-lg bg-[#b2d9be] px-4 py-2 text-sm font-medium text-[#0c120e]">질문하기</button></div></form></aside>;
}
