import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("workspace uses independent button-controlled sidebars and keeps question context out of the PDF", async () => {
  const workspace = await readFile("components/study-workspace.tsx", "utf8");
  const viewer = await readFile("components/pdf-viewer/pdf-viewer.tsx", "utf8");
  const library = await readFile("components/paper-list/paper-list.tsx", "utf8");
  const chat = await readFile("components/study-chat/study-chat.tsx", "utf8");
  const pdfPage = await readFile("components/pdf-viewer/pdf-page.tsx", "utf8");
  const tray = await readFile("components/study-tray/study-tray.tsx", "utf8");
  const account = await readFile("components/auth/account-control.tsx", "utf8");

  assert.match(workspace, /data-library-open/);
  assert.match(workspace, /data-chat-drawer-open/);
  assert.match(workspace, /data-chat-open="false"/);
  assert.match(workspace, /fixed inset-y-0 right-0 z-50/);
  assert.match(workspace, /header \+ div \+ div:not\(\.scrollbar\)/);
  assert.match(workspace, /PDF 뷰어.*논문 목록 닫기/s);
  assert.doesNotMatch(workspace, /aria-label="질의응답 바깥 영역"/);
  assert.doesNotMatch(workspace, /event\.key !== "Escape"/);
  assert.match(workspace, /paper-study-chat-open/);
  assert.match(workspace, /paper-study-chat-width/);
  assert.match(workspace, /aria-label="질의응답 패널 크기 조절"/);
  assert.match(workspace, /cursor-col-resize/);
  assert.match(workspace, /beginChatResize/);
  assert.match(workspace, /--chat-width/);

  assert.match(viewer, /onToggleLibrary/);
  assert.match(viewer, /onToggleChat/);
  assert.match(viewer, /질의응답 열기/);
  assert.match(viewer, /id="study-tray-actions"/);
  assert.doesNotMatch(viewer, /id="paper-header-actions"/);
  assert.doesNotMatch(viewer, />\{paper\.id\}</);
  assert.match(viewer, /표시된 PDF 다운로드/);
  assert.match(viewer, /표시 모두 지우기/);
  assert.match(viewer, /aria-label="PDF 주석 도구"/);
  assert.match(viewer, /label="형광펜"/);
  assert.match(viewer, /label="밑줄"/);
  assert.match(viewer, /label="영역 선택"/);
  assert.match(viewer, /label="지우개"/);
  assert.match(viewer, /tool === nextTool/);
  assert.match(viewer, /setColorMenuTool/);
  assert.match(viewer, /aria-label="주석 색상 선택"/);
  assert.doesNotMatch(viewer, /className="rounded-md px-2\.5 py-1 text-xs/);
  assert.match(viewer, /downloadAnnotatedPdf\(paper\.id, savedHighlights/);
  assert.match(viewer, /다운로드 PDF에는 포함되지 않습니다/);
  assert.match(pdfPage, /aria-label="저장된 PDF 영역"/);
  assert.match(pdfPage, /deleteMode \? "pointer-events-auto" : "pointer-events-none"/);
  assert.match(pdfPage, /border-dashed border-sky-500\/75/);
  assert.match(workspace, /clearPdfAnnotations/);
  assert.match(workspace, /highlights: \[\], areas: \[\]/);

  assert.match(library, /<select/);
  assert.match(library, /전체 카테고리/);
  assert.match(library, /논문 목록 닫기/);
  assert.match(library, /paper-study-library-category/);
  assert.match(library, /localStorage\.getItem\(PAPER_CATEGORY_STORAGE_KEY\)/);
  assert.match(library, /localStorage\.setItem\(PAPER_CATEGORY_STORAGE_KEY, tag\)/);
  assert.match(library, /activeLinkRef/);
  assert.match(library, /scrollIntoView\(\{ block: "center" \}\)/);
  assert.match(library, /<AccountControl inline\/>/);
  assert.match(account, /inline \? button/);
  assert.match(tray, /study-tray-actions/);
  assert.match(library, /논문 추가/);
  assert.match(library, />\s*편집\s*</);

  assert.match(chat, /aria-label="질문 문맥"/);
  assert.match(chat, /questionHighlights/);
  assert.match(chat, /questionAreas/);
  assert.match(chat, /onRemoveQuestionHighlight/);
  assert.match(chat, /onRemoveQuestionArea/);
  assert.match(chat, /전체 비우기/);
  assert.match(chat, /질의응답 닫기/);
  assert.match(chat, /grid grid-cols-3 gap-1/);
  assert.doesNotMatch(chat, /overflow-x-auto/);
  assert.match(chat, /페이지 요약/);
  assert.match(chat, /수식·영역 풀이/);
});
